[package]
name = "ppoprf"
version = "0.0.1"
authors = ["Alex Davidson <coela@alxdavids.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.7", default-features = false }
rand_core = "0.6.2"
rand_core_ristretto = { version="0.5.1", package="rand_core" }
bitvec = "0.22.3"
ring = "0.16.20"
curve25519-dalek = "3.2.0"
criterion = "0.3.1"
strobe-rs = "0.6.2"
strobe-rng = { path = "../strobe-rng" }

[dev-dependencies]
actix-web = "4.0.0-rc.2"

[[bench]]
name = "bench"
harness = false
