[package]
name = "ppoprf"
version = "0.0.1"
authors = ["Alex Davidson <coela@alxdavids.xyz>"]
license = "MPL-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.8.5", default-features = false }
rand_core = { version = "0.6.4", features = [ "getrandom" ] }
bitvec = "1.0.1"
curve25519-dalek =  { version = "4.0.0-rc.2", features = [ "rand_core", "serde" ] }
serde = "1.0.152"
strobe-rs = "0.8.1"
strobe-rng = { path = "../strobe-rng" }
base64 = "0.20.0"
bincode = "1.3.3"
derive_more = "0.99"
zeroize = { version = "1.5.7", features = [ "derive" ] }

[dev-dependencies]
criterion = "0.4.0"
env_logger = "0.9.3"
log = "0.4.17"
reqwest = { version = "0.11.14", features = [ "blocking", "json" ] }
dotenvy = "0.15.6"
insta = "1.28.0"
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread", "time"] }
warp = "0.3.3"

[[bench]]
name = "bench"
harness = false
