on:
  push:
    branches:
      - main
  pull_request:

name: Tests (nostd)

jobs:
  test-nofeatures:
    name: ${{matrix.rust}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        rust: [1.70.0, stable]
        os: [ubuntu-20.04]

    env:
      RUSTFLAGS: ''
      CARGO_PROFILE_DEV_DEBUG: '0' # reduce size of target directory

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Toolchain
        uses: dtolnay/rust-toolchain@0e66bd3e6b38ec0ad5312288c83e47c143e6b09e # v1
        with:
          toolchain: ${{matrix.rust}}

      - name: Cache
        uses: Swatinem/rust-cache@e207df5d269b42b69c8bc5101da26f7d31feddb4 # v2.6.2

      - name: Check
        run: cargo check --no-default-features --all-targets

      - name: Test
        run: cargo test --release --no-default-features
