on:
  push:
    branches:
      - main
  pull_request:

name: Tests

jobs:
  test:
    name: ${{matrix.rust}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        rust: [1.70.0, stable]
        os: [ubuntu-20.04]

    env:
      RUSTFLAGS: ''
      CARGO_PROFILE_DEV_DEBUG: '0' # reduce size of target directory

    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Toolchain
        run: rustup default ${{matrix.rust}}

      - name: Cache
        uses: Swatinem/rust-cache@a95ba195448af2da9b00fb742d14ffaaf3c21f43 # v2.7.0

      - name: Build
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
        with:
          command: build
          args: --release --all-targets

      - name: Test
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
        with:
          command: test
          args: --release

      - name: WASM pkg
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          cd ./star-wasm
          make build

      - name: WASM www
        run: |
          cd ./star-wasm/www
          make
