on:
  push:
    branches:
      - main
  pull_request:

name: Tests

jobs:
  wasm:
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: ''
      CARGO_PROFILE_DEV_DEBUG: '0' # reduce size of target directory

    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - name: WASM pkg
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          cd ./star-wasm
          make build

      - name: WASM www
        run: |
          cd ./star-wasm/www
          make
