on:
  push:
    branches:
      - main
  pull_request:

name: Tests

jobs:
  wasm:
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: ''
      CARGO_PROFILE_DEV_DEBUG: '0' # reduce size of target directory

    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: WASM pkg
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          cd ./star-wasm
          make build

      - name: WASM www
        run: |
          cd ./star-wasm/www
          make
